name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *' # Запускать каждые 30 минут
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: main # Или ту ветку, которую ты хочешь синхронизировать

      - name: Fetch the upstream changes
        run: git fetch upstream

      - name: Check if there are changes
        id: changes
        run: |
          git checkout main # Или ту ветку, которую ты хочешь синхронизировать
          git merge upstream/main --no-edit # Слияние изменений из оригинального репозитория
          if git diff --exit-code HEAD; then
            echo "::set-output name=has_changes::false"
          else
            echo "::set-output name=has_changes::true"
          fi

      - name: Push changes
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-email@example.com'
          git push
